services:
  gateway:
    image: registroaut.azurecr.io/gateway:latest
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - autenticacion
    environment:
      - PORT=8080
      - AUTH_SERVICE_URL=http://autenticacion:8081
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app_network

  autenticacion:
    image: registroaut.azurecr.io/autenticacion:latest
    restart: always
    expose:
      - "8081"
    environment:
      - PORT=8081
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge